version: '3'

services:
  app-installer:
    image: node:25.4.0-bullseye-slim
    working_dir: /app
    command: yarn install
    volumes:
     - ../frontend/package.json:/app/package.json
     - ../frontend/yarn.lock:/app/yarn.lock
     - ../frontend/node_modules_docker:/app/node_modules
     - ../frontend/src:/app/src
     - ../frontend/index.html:/app/index.html
     - ../frontend/tsconfig.json:/app/tsconfig.json
     - ../frontend/tsconfig.app.json:/app/tsconfig.app.json
     - ../frontend/tsconfig.node.json:/app/tsconfig.node.json
     - ../frontend/vite.config.ts:/app/vite.config.ts
     - ../frontend/public:/app/public
